### ISSUE TITLE
Main Menu

### ISSUE THREAD

**Issue by ghosalya** [ghosalya/the-gede-platformer#6]
We need a separate scene for main menu with the following buttons:

- **new game** - to start the game fresh
- **continue** - in case we have game save system. It can be as simple as "continue at the start of the latest level, with the chosen skills"
- **settings** - for various settings e.g. sound volume
- **exit** - exits the game

For a first pass, **new game** that transit to another scene, as well as **exit**, should be sufficient.

**Comment by IntricateInk** [comment]
Will create a Continue button, but propose to split save game into another issue

Settings menu should be its own issue
